apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-repo-and-argocd
  title: Criar repo + ArgoCD Application
  description: Cria repositório e application no Argo CD
spec:
  owner: user:anderson
  type: service

  parameters:
    - title: Dados do repositório
      required:
        - organization
        - project
        - repo
      properties:
        organization:
          title: Organização no Azure DevOps
          type: string
        project:
          title: Projeto no Azure DevOps
          type: string
        repo:
          title: Nome do repositório
          type: string


  steps:
    - id: publish
      name: Publicar no Azure DevOps
      action: publish:azure
      input:
        repoUrl: "dev.azure.com?organization=${{ parameters.organization }}&project=${{ parameters.project }}&repo=${{ parameters.repo }}"
        defaultBranch: desenvolvimento
        description: Projeto gerado automaticamente via Backstage
        gitCommitMessage: "Primeiro commit pelo Backstage"


    - id: criar-application-argocd
      name: Criar Application no ArgoCD
      action: fetch:plain
      input:
        url: https://argocd.suaempresa.com/api/v1/applications
        method: POST
        headers:
          Authorization: Bearer ${{ secrets.ARGOCD_AUTH_TOKEN }}
          Content-Type: application/json
        body: |
          {
            "metadata": {
              "name": "${{ parameters.nome }}",
              "namespace": "argocd"
            },
            "spec": {
              "project": "default",
              "source": {
                "repoURL": "https://github.com/sua-org/${{ parameters.nome }}.git",
                "targetRevision": "HEAD",
                "path": "manifests"
              },
              "destination": {
                "server": "https://kubernetes.default.svc",
                "namespace": "${{ parameters.nome }}"
              },
              "syncPolicy": {
                "automated": {
                  "prune": true,
                  "selfHeal": true
                },
                "syncOptions": [
                  "CreateNamespace=true"
                ]
              }
            }
          }

    - id: registrar-no-catalogo
      name: Registrar no catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['criar-repo'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repositório criado
        url: ${{ steps['criar-repo'].output.remoteUrl }}
