apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cria-sg-crossplane
  title: Criar Security Group no Crossplane
spec:
  owner: DevOps
  type: configuration

  parameters:
    # --- seus parâmetros de SG (sgName, ingressRules etc) aqui ---
    - title: Azure DevOps Repo
      required: [organization, project, repo]
      properties:
        organization:
          type: string
          title: Organização
          default: andersonmd
        project:
          type: string
          title: Projeto
          default: backstage
        repo:
          type: string
          title: Repositório
          default: sg-crossplane

  steps:
    - id: clone
      name: Clonar repositório existente
      action: azure:repo:clone
      input:
        remoteUrl: "https://dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repo }}"
        branch: desenvolvimento
        targetPath: ./workspace

    - id: fetch
      name: Gerar o YAML do SG
      action: fetch:template
      input:
        url: ./templates/cria-sg-crossplane
        targetPath: ./workspace
        values:
          sgName: ${{ parameters.sgName }}
          region: ${{ parameters.region }}
          description: ${{ parameters.description }}
          ingressRules: ${{ parameters.ingressRules }}
          egressRules: ${{ parameters.egressRules }}

    - id: push
      name: Commitar arquivo no mesmo repo
      action: azure:repo:push
      input:
        branch: desenvolvimento
        sourcePath: ./workspace
        gitCommitMessage: "Add SG ${{ parameters.sgName }} via Scaffolder"

  output:
    links:
      - title: Ver arquivo no Azure DevOps
        url: "https://dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repo }}/blob/desenvolvimento/workspace.yaml"
