apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-azure
  title: Cria Repositório no Azure DevOps
  description: Gera um novo repo dentro de um projeto existente no Azure DevOps
spec:
  owner: DevOps
  type: service

  parameters:
    - title: Informações Básicas
      required:
        - nome
        - repo
      properties:
        nome:
          type: string
          title: Nome Lógico do Projeto
        repo:
          type: string
          title: Nome do Repositório
          description: O nome do novo repo que será criado

  steps:
    - id: fetch-base
      name: Clona os arquivos do template
      action: fetch:template
      input:
        url: ./
        values:
          nome: ${{ parameters.nome }}

    - id: publish
      name: Publica no Azure DevOps
      action: publish:azure
      input:
        repoUrl: "dev.azure.com/andersonmd/backstage/${{ parameters.repo }}"
        description: "Projeto gerado pelo Backstage: ${{ parameters.nome }}"
        defaultBranch: main

  output:
    links:
      - title: Acesse no Azure DevOps
        url: "https://dev.azure.com/andersonmd/backstage/_git/${{ parameters.repo }}"
