apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-azure
  title: Projeto no Azure DevOps
  description: Cria um repositório num projeto do Azure DevOps
spec:
  owner: DevOps
  type: service

  parameters:
    - title: Informações Básicas
      required:
        - organization
        - project
        - repo
        - nome
      properties:
        organization:
          type: string
          title: Organização Azure
          default: andersonmd
        project:
          type: string
          title: Projeto Azure DevOps
          default: backstage
        repo:
          type: string
          title: Nome do repositório
        nome:
          type: string
          title: Nome lógico do serviço

  steps:
    - id: fetch-base
      name: Clona os arquivos do template
      action: fetch:template
      input:
        url: ./
        values:
          nome: ${{ parameters.nome }}

    - id: publish
      name: Publica no Azure DevOps
      action: publish:azure
      input:
        repoUrl: "dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}"
        description: Projeto gerado pelo Backstage com Scaffolder
        defaultBranch: main

  output:
    links:
      - title: Acesse o repositório
        url: "https://dev.azure.com/${{ parameters.organization }}/${{ parameters.project }}/_git/${{ parameters.repo }}"
