apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-link
  title: Exemplo de link para arquivo gerado
spec:
  owner: user:default/andersonmd26
  type: service

  parameters:
    - title: Parâmetros
      required: [nome]
      properties:
        nome:
          type: string
          title: Nome do arquivo
          default: exemplo-teste

  steps:
    - id: gerar
      name: Gerar arquivo
      action: fetch:template
      input:
        url: ./templates/exemplo-simples
        targetPath: ./output
        values:
          nome: ${{ parameters.nome }}
          descricao: Arquivo gerado via Backstage

    - id: publicar
      name: Publicar arquivo no GitHub/Azure/etc
      action: publish:github  # ou publish:azure, conforme seu provider
      input:
        repoUrl: "github.com?repo=andersonmd/teste"
        branchName: main
        sourcePath: ./output
        description: "Arquivo gerado via Backstage"
        gitCommitMessage: "Add template.yaml"

  output:
    links:
      - title: Ver arquivo gerado
        url: "https://github.com/andersonmd/teste/blob/main/template.yaml"
