apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-download
  title: Exemplo com Download
spec:
  owner: user:default/andersonmd26
  type: service

  parameters:
    - title: Parâmetros
      required: [nome]
      properties:
        nome:
          type: string
          title: Nome do arquivo
          default: arquivo-teste

  steps:
    - id: gerar
      name: Gerar arquivo
      action: fetch:template
      input:
        url: ./templates/exemplo-simples/template.yaml.njk
        targetPath: ./output
        values:
          nome: ${{ parameters.nome }}

  output:
    files:
      - title: Baixar arquivo gerado
        path: ./output/template.yaml
