apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-simples
  title: Exemplo Simples YAML
  description: Gera um arquivo yaml com nome e descrição
spec:
  owner: admin
  type: test

  parameters:
    - title: Informações básicas
      required: [nome, descricao]
      properties:
        nome:
          type: string
          title: Nome
          default: exemplo-teste
        descricao:
          type: string
          title: Descrição
          default: Arquivo gerado via Backstage

  steps:
    - id: gerar
      name: Gerar arquivo
      action: fetch:template
      input:
        url: ./templates/exemplo-simples
        targetPath: ./output
        values:
          nome: ${{ parameters.nome }}
          descricao: ${{ parameters.descricao }}

    - id: mostrar
      name: Mostrar conteúdo do arquivo
      action: debug:log
      input:
        message: |
          ====== Arquivo Gerado ======
          {{ $readFile('./output/template.yaml') }}
          ===========================

  output:
    links:
      - title: "Apenas exemplo: não há download"
        url: "#"
