apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: exemplo-simples
  title: Exemplo Simples de Template
  description: Teste mínimo para geração de arquivo via formulário
spec:
  owner: DevOps
  type: configuration

  parameters:
    - title: Dados do arquivo
      required: [nome, descricao]
      properties:
        nome:
          type: string
          title: Nome do recurso
          default: exemplo-teste
        descricao:
          type: string
          title: Descrição
          default: "Arquivo gerado via Backstage"

  steps:
    - id: gerar
      name: Gerar arquivo
      action: fetch:template
      input:
        url: ./templates/exemplo-simples/meu-arquivo.yaml.njk
        targetPath: ./output
        values:
          nome: ${{ parameters.nome }}
          descricao: ${{ parameters.descricao }}
        templateFile: meu-arquivo.yaml

    - id: ls
      name: Listar arquivos em ./output
      action: debug:log
      input:
        message: |
          Arquivos em ./output:
          {% for file in $glob('./output/*') %}{{ file }}{% endfor %}

  output:
    links:
      - title: Ver arquivo gerado
        url: ./output/meu-arquivo.yaml
